name: "Install or update EAAS"
on:
  push:
    branches: [ develop/* ]
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload blueprint
        id: upload-blueprint
        uses: jrzeszutek/cli-action@v1.2.1
        with:
          command: blueprints upload environments/eaas.yaml -b $EAAS_BLUEPRINT_ID -t default_tenant -l global
      - name: Install or update EAAS
        uses: jrzeszutek/install-or-update-action@v1.2.1
        with:
          environment-name: $EAAS_DEPLOYMENT_ID
          blueprint-id: $EAAS_BLUEPRINT_ID
          delete-old-blueprint: false
          inputs-file: .github/inputs/inputs.yaml
          labels: csys-obj-parent:$ENV_DEPLOYMENT_ID,csys-obj-type:environment
env:
  EAAS_BLUEPRINT_ID: eaas-${{ github.run_id }}
  EAAS_DEPLOYMENT_ID: eaas-ds
  # ENV_DEPLOYMENT_ID: azure
  ENV_DEPLOYMENT_ID: aws
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: ${{ secrets.CLOUDIFY_DEV_TENANT }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}